services:
  - type: web
    name: mental-chatbot
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cd my-chatbot && npm install && npm run build
    startCommand: gunicorn server:app -b 0.0.0.0:10000
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: MONGO_URI
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENV
        sync: false
    rootDir: .
