services:
  - type: web
    name: mental-chatbot
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: MONGO_URI
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENV
        sync: false
